=== Crazyers/zxl/zxl-mapper/src/main/resources/cn/zxl/mapper/config/mapper-1.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns="http://zxl.cn/schema/mapper" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://zxl.cn/schema/mapper">

	<xsd:import namespace="http://www.w3.org/XML/1998/namespace" />

	<!-- Top-level <mapper> tag -->
	<xsd:element name="mapper">
		<xsd:complexType>
			<xsd:sequence minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="rule" minOccurs="0" maxOccurs="unbounded"></xsd:element>
				<xsd:element ref="map" minOccurs="0" maxOccurs="unbounded"></xsd:element>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="rule">
		<xsd:annotation>
			<xsd:documentation>rule元素定义一套映射规则</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="relation" minOccurs="1" maxOccurs="unbounded"></xsd:element>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>rule元素id</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="left-type" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>映射左侧对象的类型</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="right-type" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>映射右侧对象的类型</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="relation">
		<xsd:annotation>
			<xsd:documentation>relation元素定义字段级别的映射规则</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:attribute name="left-name" use="required" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>左侧属性名</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="right-name" use="required" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>右侧属性名</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="date-format" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>当string与date互相转换时可指定该元素，默认格式为yyyy-MM-dd</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="rule" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>当属性为bean类型时，可以指定该元素作为嵌套规则</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="reverse" type="xsd:boolean">
				<xsd:annotation>
					<xsd:documentation>当rule属性被指定时，可指定该元素定义规则的方向</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:element name="map">
		<xsd:annotation>
			<xsd:documentation>一个map定义一个转换规则，在执行转换时，需要指定map的id</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="set" minOccurs="1" maxOccurs="unbounded"></xsd:element>
			</xsd:sequence>
			<xsd:attribute name="id" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>map对象id</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="rule" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>指定map对象所基于的映射规则，如果不指定，则必须指定type属性</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="type" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation>该属性不为空时表示的是两个类型相同对象的转换</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="direction" type="directionEnum">
				<xsd:annotation>
					<xsd:documentation>指定rule对象的方向</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

	<xsd:simpleType name="directionEnum">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="left-to-right"></xsd:enumeration>
			<xsd:enumeration value="right-to-left"></xsd:enumeration>
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:element name="set">
		<xsd:annotation>
			<xsd:documentation>一个set对象表示字段级别的具体转换规则</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:attribute name="left-field-name" type="xsd:string" use="required">
				<xsd:annotation>
					<xsd:documentation>指定一组字段转换，通过左边的属性名定义。支持通配符‘*’，如果指定嵌套字段，可使用‘.’隔开。</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="if-source-is-not-null" type="xsd:boolean">
				<xsd:annotation>
					<xsd:documentation>当源不为空时才转换</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="if-source-is-not-empty" type="xsd:boolean">
				<xsd:annotation>
					<xsd:documentation>当源不为空时才转换</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="if-target-is-null" type="xsd:boolean">
				<xsd:annotation>
					<xsd:documentation>当目标为空时才转换</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
			<xsd:attribute name="if-target-is-empty" type="xsd:boolean">
				<xsd:annotation>
					<xsd:documentation>当目标为空时才转换</xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>

</xsd:schema>

=== Crazyers/zxl/zxl-mapper/src/test/resources/mapper/mapper.xml
<?xml version="1.0" encoding="UTF-8"?>
<mapper xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.creditease.cn/schema/mapper" xsi:schemaLocation="http://www.creditease.cn/schema/mapper http://www.creditease.cn/schema/mapper/mapper-1.0.xsd">
	<rule id="testRule" left-type="cn.zxl.mapper.Book" right-type="cn.zxl.mapper.Note">
		<relation left-name="id" right-name="idNote"/>
		<relation left-name="age" right-name="ageNote" />
		<relation left-name="date" right-name="date" date-format="yyyy-MM-dd"/>
		<relation left-name="innerBook" right-name="innerNote" rule="testInnerRule"/>
		<relation left-name="name" right-name="nameNote" />
		<relation left-name="innerNote" right-name="innerNote"/>
	</rule>
	
	<rule id="testInnerRule" left-type="cn.zxl.mapper.InnerBook" right-type="cn.zxl.mapper.InnerNote">
		<relation left-name="name" right-name="id"/>
		<relation left-name="summary" right-name="field"/>
		<relation left-name="number" right-name="summary"/>
	</rule> 
	
	<rule id="testReverseRule" left-type="cn.zxl.mapper.Book" right-type="cn.zxl.mapper.Note">
		<relation left-name="id" right-name="idNote"/>
		<relation left-name="age" right-name="ageNote" />
		<relation left-name="date" right-name="date" date-format="yyyy-MM-dd"/>
		<relation left-name="innerBook" right-name="innerNote" rule="testInnerReverseRule" reverse="true"/>
		<relation left-name="name" right-name="nameNote" />
	</rule>
	
	<rule id="testInnerReverseRule" left-type="cn.zxl.mapper.InnerNote" right-type="cn.zxl.mapper.InnerBook">
		<relation right-name="name" left-name="id"/>
		<relation right-name="summary" left-name="field"/>
		<relation right-name="number" left-name="summary"/>
	</rule>
	
	<map id="testEmptyRuleMap" direction="left-to-right" rule="testRule" >
		<set left-field-name="id" />
		<set left-field-name="age" if-target-is-null="true"/>
		<set left-field-name="date" />
		<set left-field-name="name" if-target-is-empty="true"/>
		<set left-field-name="innerNote.id" if-source-is-not-empty="true"/>
		<set left-field-name="innerNote.field" />
	</map>

	<map id="testMap" direction="left-to-right" rule="testRule" >
		<set left-field-name="id" />
		<set left-field-name="age" if-target-is-null="true"/>
		<set left-field-name="date" />
		<set left-field-name="name" if-target-is-empty="true"/>
		<set left-field-name="innerBook.name" if-source-is-not-empty="true"/>
		<set left-field-name="innerBook.number" />
	</map>
	
	<map id="testReverseMap" direction="left-to-right" rule="testReverseRule" >
		<set left-field-name="id" />
		<set left-field-name="age" if-target-is-null="true"/>
		<set left-field-name="date" />
		<set left-field-name="name" if-target-is-empty="true"/>
		<set left-field-name="innerBook.name" if-source-is-not-empty="true"/>
		<set left-field-name="innerBook.number" />
	</map>
	
	<map type="cn.zxl.mapper.Book" id="testTypeRule1">
		<set left-field-name="*"/>
	</map>
	
	<map type="cn.zxl.mapper.Book" id="testTypeRule2">
		<set left-field-name="age"/>
		<set left-field-name="innerBook.*"/>
	</map>
	
	<map type="cn.zxl.mapper.Book" id="testTypeRule3">
		<set left-field-name="*" if-target-is-null="true"/>
	</map>

</mapper>
